[COURSE HEADER]
VERSION = 0
UNITS = ENGLISH
DESCRIPTION = 10 Minute Interval,0.97,16. Created by 3238.
FILE NAME = none
MINUTES	FTP
[END COURSE HEADER]

[COURSE DATA]
0	97
10	97
[END COURSE DATA]

[COURSE TEXT]
[END COURSE TEXT]

[INTERVAL DATA]
0	600	Workout
0	600	Threshold 1
[END INTERVAL DATA]

[MODE DATA]
[END MODE DATA]

