[COURSE HEADER]
VERSION = 0
UNITS = ENGLISH
DESCRIPTION = 20 Minute Interval,0.97,31. Created by 3238.
FILE NAME = none
MINUTES	FTP
[END COURSE HEADER]

[COURSE DATA]
0	97
20	97
[END COURSE DATA]

[COURSE TEXT]
[END COURSE TEXT]

[INTERVAL DATA]
0	1200	Workout
0	1200	Threshold 1
[END INTERVAL DATA]

[MODE DATA]
[END MODE DATA]

